### ISSUE TITLE
Catkinize pr2_self_test

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_self_test#2]
Catkinize and release pr2_self_test. Depends on catkinizing and releasing:
- [x] pr2_mannequin_mode (from PR2/pr2_apps#2)

**Comment by UltronDestroyer** [comment]
Self note for catkinization. @TheDash

**Comment by UltronDestroyer** [comment]
Catkinized on hydro-devel using the hydro-devel of pr2_mannequin_mode
